### ISSUE TITLE
[suggestion] Title Formatting

### ISSUE THREAD

**Issue by ntorga** [digitalsparky/rocketchat-whmcs#1]
Hi there,

First, thank you for the work and for releasing the code. I know it's silly, but I noticed the notification title is a bit different from the one used by the others WHMCS integration, so I adjusted it slightly:

![screenshot_2018-09-05_22-10-32](https://user-images.githubusercontent.com/14931603/45129210-cf6bff80-b158-11e8-8143-b4fbd3f5a09e.png)

Not sure if you'll like it, so I'm creating this topic before sending a PR. Please, let me know if you feel it'll be a good addition.

Regards,
Northon

**Comment by digitalsparky** [comment]
Hi Northon,

Thanks for getting in contact, sorry I didn't respond, for some reason I didn't get a notification (thanks GitHub....)

It looks good, please send a PR and I'll integrate.

Have a great day!

Matt
